/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/hydrator/wrangler.jsonc --include-runtime=false` (hash: 7138f93097c951c4c808f6a7be597a56)
interface __BaseEnv_Env {
	CREDIT_INDEX: R2Bucket;
	DB: D1Database;
	R2_READ_LIMIT: "9000000";
	R2_DAILY_READ_LIMIT: "720";
	D1_DAILY_WRITE_LIMIT: "50000";
	RESOURCE_GUARD: DurableObjectNamespace /* ResourceGuard from timbre-palette-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/hydrator/src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_READ_LIMIT" | "R2_DAILY_READ_LIMIT" | "D1_DAILY_WRITE_LIMIT">> {}
}
