"""Source-backed editorial fichas used by the mock catalog."""

from palette_api.schemas import InstrumentResource

EDITORIAL_INSTRUMENTS = tuple(
    InstrumentResource.model_validate(data)
    for data in [{'data_source': 'mock',
  'catalog_version': 'mock-0.1.0',
  'image_catalog_version': 'images-0.1.0',
  'slug': 'acoustic-guitar',
  'name': 'Violão',
  'kind': 'instrument',
  'family_slug': 'plucked-strings',
  'description': 'Instrumento de cordas dedilhadas com caixa de ressonância acústica.',
  'sound_production': 'As cordas vibram ao serem dedilhadas ou palhetadas; o tampo e a caixa de '
                      'ressonância irradiam o som.',
  'common_roles': ['harmonia', 'melodia', 'acompanhamento'],
  'related_slugs': ['plucked-strings'],
  'sections': [{'id': 'instrument-acoustic-guitar-curiosity',
                'kind': 'curiosity',
                'text': 'O acervo do LABEET registra o violão no conjunto que acompanhava a '
                        'lambada paraense entre 1975 e 1978, ao lado de tambor carimbó, pandeiro, '
                        'reco-reco, marimba e banjo. Sua presença no acervo vai além do samba e da '
                        'MPB.',
                'content_type': 'editorial_summary',
                'status': 'sourced',
                'review': {'source_metadata_verified': True,
                           'claim_support_verified': False,
                           'reviewed_at': None,
                           'reviewer': None,
                           'editorial_note': None},
                'citations': [{'source_id': 'ufpb-labeet-reco-reco',
                               'locator': 'Parágrafo sobre lambada do Pará (entre 1975 e 1978).',
                               'note': 'Resumo editorial da passagem indicada; não implica revisão '
                                       'acadêmica ou endosso institucional.'}]}],
  'sources': [{'id': 'ufpb-labeet-reco-reco',
               'title': 'Reco-reco — Acervo Brazil Instrumentarium',
               'contributors': ['Alice L. Satomi', 'Gabriel da Rosa Seixas (tradução)'],
               'publisher': 'Universidade Federal da Paraíba — LABEET',
               'publication_date': '2016-09-12',
               'url': 'https://www.ctdr.ufpb.br/labeet/contents/paginas/acervo-brazinst/copy_of_idiofones/reco-reco',
               'accessed_at': '2026-09-14',
               'verified_at': '2026-09-14',
               'locator': 'Verbete Reco-reco',
               'source_type': 'university',
               'language': 'pt-BR',
               'license': None,
               'note': 'Fonte consultada diretamente. Citações limitadas aos conjuntos descritos '
                       'no verbete; não é um verbete específico dos instrumentos citados.',
               'metadata_verified': True}],
  'further_reading': [],
  'image': None,
  'tone': None},
 {'data_source': 'mock',
  'catalog_version': 'mock-0.1.0',
  'image_catalog_version': 'images-0.1.0',
  'slug': 'cavaquinho',
  'name': 'Cavaquinho',
  'kind': 'instrument',
  'family_slug': 'plucked-strings',
  'description': 'Pequeno instrumento de cordas dedilhadas e caixa de ressonância acústica.',
  'sound_production': 'As cordas dedilhadas ou palhetadas transmitem a vibração ao tampo e à caixa '
                      'de ressonância.',
  'common_roles': ['harmonia', 'ritmo', 'acompanhamento'],
  'related_slugs': ['plucked-strings'],
  'sections': [{'id': 'instrument-cavaquinho-curiosity',
                'kind': 'curiosity',
                'text': 'Na gravação da Lapinha de Valdemar de 8 de dezembro de 1972, catalogada '
                        'pelo LABEET, o cavaquinho acompanha as pastoras junto de bandolim, violão '
                        'e pandeiro. O registro documenta seu uso no pastoril, além dos contextos '
                        'de samba e choro.',
                'content_type': 'editorial_summary',
                'status': 'sourced',
                'review': {'source_metadata_verified': True,
                           'claim_support_verified': False,
                           'reviewed_at': None,
                           'reviewer': None,
                           'editorial_note': None},
                'citations': [{'source_id': 'ufpb-labeet-lapinha',
                               'locator': 'Audios: AFB 07; gravação 08/12/1972; UFPB/BC-FR7003; '
                                          'T42 T43.',
                               'note': 'Resumo editorial da passagem indicada; não implica revisão '
                                       'acadêmica ou endosso institucional.'}]}],
  'sources': [{'id': 'ufpb-labeet-lapinha',
               'title': 'Pastoril ou Lapinha — Acervo PDMCP',
               'contributors': [],
               'publisher': 'Universidade Federal da Paraíba — LABEET',
               'publication_date': None,
               'url': 'https://www.ctdr.ufpb.br/labeet/contents/paginas/acervo-pdmcp/pastoril-ou-lapinha/',
               'accessed_at': '2026-09-14',
               'verified_at': '2026-09-14',
               'locator': 'Audios: AFB 07, Tape 42 e Tape 43 — 3; T42 T43',
               'source_type': 'university',
               'language': 'pt-BR',
               'license': None,
               'note': 'Registro de catálogo da Lapinha de Valdemar, datado de 08/12/1972. A data '
                       'da gravação não é a data de publicação da página; autoria individual não '
                       'atribuída ao registro.',
               'metadata_verified': True}],
  'further_reading': [],
  'image': None,
  'tone': None},
 {'data_source': 'mock',
  'catalog_version': 'mock-0.1.0',
  'image_catalog_version': 'images-0.1.0',
  'slug': 'pandeiro',
  'name': 'Pandeiro',
  'kind': 'instrument',
  'family_slug': 'percussion',
  'description': 'Tambor de aro com uma membrana e pequenas peças metálicas chamadas soalhas.',
  'sound_production': 'Golpes e fricção excitam a membrana; o movimento do aro também faz vibrar '
                      'as soalhas.',
  'common_roles': ['ritmo', 'acentuação', 'textura'],
  'related_slugs': ['percussion'],
  'sections': [{'id': 'instrument-pandeiro-curiosity',
                'kind': 'curiosity',
                'text': 'O verbete do LABEET mostra que o pandeiro pode funcionar como '
                        'membranofone quando sua pele é tocada, ou como idiofone quando apenas as '
                        'soalhas soam ao ser sacudido. Um mesmo instrumento reúne duas formas de '
                        'produzir som.',
                'content_type': 'editorial_summary',
                'status': 'sourced',
                'review': {'source_metadata_verified': True,
                           'claim_support_verified': False,
                           'reviewed_at': None,
                           'reviewer': None,
                           'editorial_note': None},
                'citations': [{'source_id': 'ufpb-labeet-pandeiro',
                               'locator': 'Descrição da pele, das soalhas e classificação conforme '
                                          'a execução.',
                               'note': 'Resumo editorial da passagem indicada; não implica revisão '
                                       'acadêmica ou endosso institucional.'}]}],
  'sources': [{'id': 'ufpb-labeet-pandeiro',
               'title': 'Pandeiro — Acervo Brazil Instrumentarium',
               'contributors': ['Gabriel da Rosa Seixas'],
               'publisher': 'Universidade Federal da Paraíba — LABEET',
               'publication_date': '2017-02-05',
               'url': 'https://www.ufpb.br/labeet/contents/acervos/categorias/membranofones/pandeiro',
               'accessed_at': '2026-09-14',
               'verified_at': '2026-09-14',
               'locator': 'Verbete Pandeiro: descrição e classificação',
               'source_type': 'university',
               'language': 'pt-BR',
               'license': None,
               'note': 'Verbete consultado diretamente; referências bibliográficas internas não '
                       'são apresentadas como obras consultadas.',
               'metadata_verified': True}],
  'further_reading': [],
  'image': None,
  'tone': None},
 {'data_source': 'mock',
  'catalog_version': 'mock-0.1.0',
  'image_catalog_version': 'images-0.1.0',
  'slug': 'surdo',
  'name': 'Surdo',
  'kind': 'instrument',
  'family_slug': 'percussion',
  'description': 'Tambor de registro grave usado para marcação rítmica em conjuntos de percussão.',
  'sound_production': 'A percussão da membrana põe em vibração a pele e o ar do corpo ressonante; '
                      'o abafamento controla a duração do som.',
  'common_roles': ['ritmo', 'marcação', 'linha grave'],
  'related_slugs': ['percussion'],
  'sections': [{'id': 'instrument-surdo-curiosity',
                'kind': 'curiosity',
                'text': 'No verbete de reco-reco, o LABEET situa o surdo em conjuntos de carnaval, '
                        'sambas, marchinhas e samba de morro do Rio de Janeiro. Ali ele aparece ao '
                        'lado de caixa, repique, tamborim, pandeiro e cuíca, compondo um conjunto '
                        'de membranofones.',
                'content_type': 'editorial_summary',
                'status': 'sourced',
                'review': {'source_metadata_verified': True,
                           'claim_support_verified': False,
                           'reviewed_at': None,
                           'reviewer': None,
                           'editorial_note': None},
                'citations': [{'source_id': 'ufpb-labeet-reco-reco',
                               'locator': 'Parágrafo sobre danças e músicas urbanas modernas e '
                                          'seus membranofones.',
                               'note': 'Resumo editorial da passagem indicada; não implica revisão '
                                       'acadêmica ou endosso institucional.'}]}],
  'sources': [{'id': 'ufpb-labeet-reco-reco',
               'title': 'Reco-reco — Acervo Brazil Instrumentarium',
               'contributors': ['Alice L. Satomi', 'Gabriel da Rosa Seixas (tradução)'],
               'publisher': 'Universidade Federal da Paraíba — LABEET',
               'publication_date': '2016-09-12',
               'url': 'https://www.ctdr.ufpb.br/labeet/contents/paginas/acervo-brazinst/copy_of_idiofones/reco-reco',
               'accessed_at': '2026-09-14',
               'verified_at': '2026-09-14',
               'locator': 'Verbete Reco-reco',
               'source_type': 'university',
               'language': 'pt-BR',
               'license': None,
               'note': 'Fonte consultada diretamente. Citações limitadas aos conjuntos descritos '
                       'no verbete; não é um verbete específico dos instrumentos citados.',
               'metadata_verified': True}],
  'further_reading': [],
  'image': None,
  'tone': None},
 {'data_source': 'mock',
  'catalog_version': 'mock-0.1.0',
  'image_catalog_version': 'images-0.1.0',
  'slug': 'tamborim',
  'name': 'Tamborim',
  'kind': 'instrument',
  'family_slug': 'percussion',
  'description': 'Pequeno tambor de aro e uma membrana, tocado com baqueta.',
  'sound_production': 'A baqueta percute a membrana esticada sobre o aro, produzindo ataques '
                      'curtos e definidos.',
  'common_roles': ['ritmo', 'acentuação', 'contracanto'],
  'related_slugs': ['percussion'],
  'sections': [{'id': 'instrument-tamborim-curiosity',
                'kind': 'curiosity',
                'text': 'O LABEET distingue dois tipos de tamborim: um artesanal, de corpo de '
                        'madeira mais profundo, usado em congada e moçambique, e outro comercial, '
                        'de aro baixo de metal ou acrílico, comum nas baterias de escolas de '
                        'samba.',
                'content_type': 'editorial_summary',
                'status': 'sourced',
                'review': {'source_metadata_verified': True,
                           'claim_support_verified': False,
                           'reviewed_at': None,
                           'reviewer': None,
                           'editorial_note': None},
                'citations': [{'source_id': 'ufpb-labeet-tamborim',
                               'locator': 'Primeiro tipo artesanal e segundo tipo comercial.',
                               'note': 'Resumo editorial da passagem indicada; não implica revisão '
                                       'acadêmica ou endosso institucional.'}]}],
  'sources': [{'id': 'ufpb-labeet-tamborim',
               'title': 'Tamborim — Acervo Brazil Instrumentarium',
               'contributors': ['Alice L. Satomi', 'Gabriel da Rosa Seixas (tradução)'],
               'publisher': 'Universidade Federal da Paraíba — LABEET',
               'publication_date': '2016-10-10',
               'url': 'https://www.ctdr.ufpb.br/labeet/contents/acervos/categorias/membranofones/tamborim',
               'accessed_at': '2026-09-14',
               'verified_at': '2026-09-14',
               'locator': 'Verbete Tamborim: primeiro e segundo tipos',
               'source_type': 'university',
               'language': 'pt-BR',
               'license': None,
               'note': 'Verbete consultado diretamente; distingue o tipo artesanal do tamborim '
                       'comercial das baterias de escolas de samba.',
               'metadata_verified': True}],
  'further_reading': [],
  'image': None,
  'tone': None},
 {'data_source': 'mock',
  'catalog_version': 'mock-0.1.0',
  'image_catalog_version': 'images-0.1.0',
  'slug': 'cuica',
  'name': 'Cuíca',
  'kind': 'instrument',
  'family_slug': 'percussion',
  'description': 'Tambor de fricção com uma haste presa à membrana pelo lado interno.',
  'sound_production': 'A fricção da haste transmite vibração à membrana; a pressão dos dedos sobre '
                      'a pele modifica o som.',
  'common_roles': ['ritmo', 'fraseado', 'textura'],
  'related_slugs': ['percussion'],
  'sections': [{'id': 'instrument-cuica-curiosity',
                'kind': 'curiosity',
                'text': 'A cuíca aparece no acervo Brazil Instrumentarium do LABEET entre os '
                        'membranofones que acompanham o reco-reco industrial no carnaval, no '
                        'samba, nas marchinhas e no samba de morro carioca. O registro evidencia '
                        'seu lugar em conjuntos, junto de surdo, caixa e repique.',
                'content_type': 'editorial_summary',
                'status': 'sourced',
                'review': {'source_metadata_verified': True,
                           'claim_support_verified': False,
                           'reviewed_at': None,
                           'reviewer': None,
                           'editorial_note': None},
                'citations': [{'source_id': 'ufpb-labeet-reco-reco',
                               'locator': 'Parágrafo sobre danças e músicas urbanas modernas e '
                                          'seus membranofones.',
                               'note': 'Resumo editorial da passagem indicada; não implica revisão '
                                       'acadêmica ou endosso institucional.'}]}],
  'sources': [{'id': 'ufpb-labeet-reco-reco',
               'title': 'Reco-reco — Acervo Brazil Instrumentarium',
               'contributors': ['Alice L. Satomi', 'Gabriel da Rosa Seixas (tradução)'],
               'publisher': 'Universidade Federal da Paraíba — LABEET',
               'publication_date': '2016-09-12',
               'url': 'https://www.ctdr.ufpb.br/labeet/contents/paginas/acervo-brazinst/copy_of_idiofones/reco-reco',
               'accessed_at': '2026-09-14',
               'verified_at': '2026-09-14',
               'locator': 'Verbete Reco-reco',
               'source_type': 'university',
               'language': 'pt-BR',
               'license': None,
               'note': 'Fonte consultada diretamente. Citações limitadas aos conjuntos descritos '
                       'no verbete; não é um verbete específico dos instrumentos citados.',
               'metadata_verified': True}],
  'further_reading': [],
  'image': None,
  'tone': None}]
)
